project:
  type: website
  output-dir: .

website:
  navbar:
    search: false
    background: '#f8f9fa'
    left:
      - text: "Home"
        file: index.qmd
      - text: "Dictionary"
        file: dictionary.qmd
    tools:
      - icon: download
        menu:
          - text: Download data
            url: ./data/rutul_dict.xlsx
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Affenmilchmann/rutul-dict